# Generated by Django 5.1 on 2024-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
