# Generated by Django 5.1 on 2024-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesearch', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
